ci/cd:  fail deployment of data validation explorer instance if no runner is available for 5 min

diff --git a/.github/workflows/update-datavalidation.yml b/.github/workflows/update-datavalidation.yml
--- a/.github/workflows/update-datavalidation.yml
+++ b/.github/workflows/update-datavalidation.yml
@@ -12,5 +12,15 @@ jobs:
   restart-data-validation:
     runs-on: siibra-data-validation
     steps:
-    - run: |
-        /bin/bash -c "cd /softwares/software && ./restart.sh"
+      - name: Check runner availability
+        id: check_runner
+        run: |
+          echo "Checking if the runner is available..."
+          if ! timeout 300 bash -c 'while true; do sleep 1; done'; then
+            echo "Runner not available for 5 minutes, failing the job."
+            exit 1  # Fail the job if the runner is not available
+          fi
+      - name: restart data validation
+        id: restart_data_validation
+        run: |
+          /bin/bash -c "cd /softwares/software && ./restart.sh"
